In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('hiring.csv')

In [3]:
# experience
df['experience'].fillna(0, inplace=True)
df.isna().sum()

experience         0
test_score         1
interview_score    0
salary             0
dtype: int64

In [4]:
df['test_score'] = df['test_score'].fillna(df['test_score'].mean())
df.isna().sum()

experience         0
test_score         0
interview_score    0
salary             0
dtype: int64

In [5]:
X = df.iloc[:,:-1]
X

experience  test_score  interview_score
0          0    8.000000                9
1          0    8.000000                6
2       five    6.000000                7
3        two   10.000000               10
4      seven    9.000000                6
5      three    7.000000               10
6        ten    7.857143                7
7     eleven    7.000000                8

In [6]:
def conv(x):
    dict = {
        0 : 0,
        'five' : 5,
        'two' : 2,
        'seven' : 7,
        'three' : 3,
        'ten' : 10,
        'eleven' : 11
    }
    return dict[x]

In [7]:
X['experience'] = X['experience'].apply(lambda x : conv(x))
X

experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

In [8]:
y = df.iloc[:,-1]
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [9]:
# Modeling

from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [10]:
# Fit the model
lr.fit(X, y)

LinearRegression()

In [11]:
# Prediction Phase

y_pred = lr.predict(X)
y_pred

array([52313.61238494, 45722.68644263, 58231.95591138, 63991.7318464 ,
       67429.06277517, 61080.55179794, 75922.72532666, 79307.67351488])

In [12]:
list(zip(y, y_pred))

[(50000, 52313.612384941014),
 (45000, 45722.68644262675),
 (60000, 58231.95591138131),
 (65000, 63991.731846400544),
 (70000, 67429.06277516519),
 (62000, 61080.55179794243),
 (72000, 75922.72532666178),
 (80000, 79307.67351488101)]

In [13]:
from sklearn.metrics import r2_score
r2_score(y, y_pred)

0.9639958361860578

In [14]:
lr.predict([[3,9,7]])

F:\anaconda extracts\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([58315.5019167])

In [15]:
lr.predict([[10,2,3]])

F:\anaconda extracts\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([55930.47274854])

In [16]:
# Here, we will save the 'lr' model to disk as 'model.py'

import pickle
pickle.dump(lr,open('model.pkl','wb'))
# Dump this model by the name 'model.pkl' in the sytems HDD/SSD and while doing this
# write this file using 'write bytes' mode
print("Model saved successfully!")

Model saved successfully!


In [17]:
import pickle

model_for_client = pickle.load(open('model.pkl','rb'))
# rb - read bytes
model_for_client

LinearRegression()